title: Since Marketing
email: info@since.com
description: Since Marketing - Agencia de Marketing Digital especializada en estrategias de crecimiento para empresas en Latinoam√©rica.
baseurl: ""
url: "https://revisemos.com"
lang: "es"

social:
  instagram: https://instagram.com/since
  facebook: https://facebook.com/since
  linkedin: https://linkedin.com/company/since

markdown: kramdown

plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page/:num/"

permalink: :slug

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore: []
  envs: []
  blanklines: false
  profile: false
  startings: []

collections:
  redirects:
    output: true
  servicios:
    output: true
    permalink: /servicios/:path
  posts:
    output: true
    permalink: /blog/:slug

# Opciones adicionales
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Since Marketing"
      comments: true


category_order:
  - primera-categoria
  - segunda-categoria
  - tercera-categoria